AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for running Kittens Carousel Static Website on EC2. 
  Kittens Carousel Static Website will be deployed on Amazon Linux 2023 EC2 Instance with custom 
  security group which allows http connections on port 80 and ssh port 22 from anywhere. Kittens Carousel Static Website
  is downloaded from my Public Github repository, then deployed on Apache Web Server

Parameters:
  keypair:
    Description: Choose your keypair
    Type: AWS::EC2::KeyPair::KeyName
    Default: hh2025

Resources: 
  mySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows ssh and http  # Required
      GroupName: hasan-sec-grp-aws20tr
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
  
  mywebserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00a929b66ed6e0de6  # Eğer bu doğru AMI ID ise, kalabilir.
      InstanceType: t2.micro
      KeyName: !Ref keypair
      SecurityGroupIds: 
        - !Ref mySecGrp
      Tags: 
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData: !Base64 |
          #! /bin/bash
          dnf update -y
          #! /bin/bash
          dnf update -y
          dnf install httpd -y
          FOLDER="https://raw.githubusercontent.com/hasan-hira/aws-projects-20/refs/heads/main/101-kittens-carousel-static-website-ec2/static-web"
          cd /var/www/html/
          wget ${FOLDER}/index.html
          wget ${FOLDER}/cat0.jpg
          wget ${FOLDER}/cat1.jpg
          wget ${FOLDER}/cat2.jpg
          systemctl start httpd
          systemctl enable httpd

Outputs:
  WebSiteURL:
    Description: URL of website
    Value: !Sub
      - http://${PublicDnsName}
      - PublicDnsName: !GetAtt mywebserver.PublicDnsName
